services:
  - type: web
    name: neetcode-v1
    runtime: image
    region: oregon
    plan: free
    image:
      url: node:18
    buildCommand: |
      apt-get update -qq
      apt-get install -y -qq golang-go
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000